namespace BuzzwordService.Helpers
{
    public class TechnologyBuzzwordHelper : IBuzzwordHelper
    {       
        public string[] GetBuzzwords()
        {
            return new string[] {
                "4G",
                "Aggregator",
                "Agile",
                "Ajax",
                "Algorithm",
                "Benchmarking",
                "Back-end",
                "Beta",
                "Big data - larger data sets than last month",
                "Bleeding edge",
                "Blog – plus various other words that incorporate 'blog'",
                "Bring your own Device - use of personal equipment (usually mobile) in a work environment",
                "Bricks-and-clicks",
                "Clickthrough",
                "Cloud",
                "CloudOps",
                "Collaboration",
                "Content management",
                "Content Management System – also known as CMS.",
                "Convergence",
                "Cross-platform",
                "Cyber-physical Systems (CSP)",
                "Datafication",
                "Data mining - any kind of data collection or analysis, even simple statistics such as taking averages on large data sets",
                "Data science",
                "Deep dive",
                "Deep web - used interchageably with 'Dark web' even though they're not the same",
                "Design pattern",
                "DevOps",
                "Digital divide",
                "Digital Remastering",
                "Digital Rights Management – also known as DRM.",
                "Digital signage",
                "Disruptive Technologies",
                "Document management",
                "Dot-bomb",
                "____-Driven Development",
                "E-learning",
                "End-to-End",
                "Engine",
                "Enterprise Content Management – also known as ECM.",
                "Enterprise Service Bus – also known as ESB.",
                "Evolution - Often use ambiguously in political or sociological arguments in reference to theories of social Darwinism. (e.x. 'Society has evolved.')",
                "Framework",
                "Folksonomy",
                "Fuzzy logic",
                "Growth Hacking",
                "HTML5",
                "Immersion",
                "Information superhighway / Information highway",
                "Internet of Things",
                "Innovation",
                "Mashup",
                "Microservices",
                "Mobile",
                "Modularity",
                "Nanotechnology",
                "Netiquette",
                "NFV- Network Function virtualization",
                "Next Generation (also 'NextGen')",
                "Object-Oriented Programming",
                "Omnichannel",
                "Pandering",
                "Parsing",
                "PaaS",
                "Podcasting",
                "Portal",
                "Real-time",
                "Responsive Web Design",
                "Sensorization",
                "SaaS",
                "Scalability",
                "Skeuomorphic",
                "Social bookmarking",
                "Social software",
                "Software Defined _blank_",
                "SDN- Software defined Networking",
                "Spam",
                "Struts",
                "Sync-up",
                "Systems Development Life-Cycle",
                "Tagging",
                "Think outside the box",
                "Thought Leader",
                "Transmedia",
                "UC - Unified Communications",
                "User generated content",
                "Viral",
                "Virtualization",
                "Vlogging",
                "Vortal",
                "Web 2.0",
                "Webinar",
                "Weblog",
                "Web services",
                "Wikiality",
                "Workflow"
            };
        }
    }
}